### ISSUE TITLE
@model is deprecated

### ISSUE THREAD

**Issue by AlexJuca** [manuelernesto/myplacard_jetpack_compose#1]
https://github.com/manuelernesto/myplacard_jetpack_compose/blob/9ac9c5b2cf5462813b2d6424b18a076b8c1e38ea/app/src/main/java/io/github/manuelernesto/myplacard_jetpackcompose/Team.kt#L7

@Model annotation has been deprecated in the latest version of jetpack compose. we can use the state and mutableStateOf as alternatives

**Comment by manuelernesto** [comment]
@AlexJuca yes, and I'm replacing with mutableStateOf. thanks 🙌🏿

**Comment by manuelernesto** [comment]
@AlexJuca we already update the code, removing the deprecated Model annotation, and replace it with the state.
